In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

import nltk
import os

In [2]:
# Clear any custom paths
nltk.data.path = []

# Download to the default location with force option
nltk.download('punkt', quiet=False)
nltk.download('punkt_tab')

# Print path to verify
print("NLTK data paths:", nltk.data.path)

NLTK data paths: []

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\GROUP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\GROUP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [3]:
data = pd.read_csv("./DATA/Reviews.csv")
print(data.shape)
data.head()

(568454, 10)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [9]:
new_review = data[:1000]
new_review.head(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...

In [12]:
# new_review.to_csv("./DATA/new_review.csv")
new_review.to_excel("./DATA/new_review.xlsx")

In [11]:
new_review['Text'][0]

'I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.'

In [ ]:
ax = data['Score'].value_counts().sort_index() \
  .plot(kind='bar',
    title='Count of Reviews by Stars',
    figsize=(10, 5))
ax.set_xlabel('Review Stars')
plt.show()

In [ ]:
example = data['Text'][50]
example

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
nltk.word_tokenize(example)

In [ ]:
# Try tokenizing with explicit error handling
try:
  tokens = word_tokenize(example)
  print(tokens[:10])
except LookupError as e:
  print("Error:", e)
  
  # If it still doesn't work, use the simple tokenizer as fallback
  print("\nFalling back to basic tokenization:")
  basic_tokens = example.split()
  print(basic_tokens[:10])

In [ ]:
tagged = nltk.pos_tag(tokens)
tagged[:10]